config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  devise_for :users

  resources :genres, only: %i[index show new create update] do
    resources :collections, only: %i[new]
  end

  resources :collections, only: %i[show create update] do
    resources :writings, only: %i[new]
  end

  resources :writings, only: %i[index show create edit update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/genre.rb
class Genre < ApplicationRecord

  # === relationships

  has_many :collections,
           dependent: :restrict_with_exception
  has_many :published_collections,
           -> { where('collections.published_at IS NOT NULL') },
           class_name: 'Collection',
           dependent: :restrict_with_exception

  # === validations

  validates :name, presence: true

  # === scopes

  scope :alpha_order, -> { order(:name) }
  scope :published, -> { where.not(published_at: nil) }

  # === class methods

  # === instance methods

  def published?
    published_at.present?    
  end

  def publish
    return if archived? || published?

    update(published_at: Time.zone.now)
  end

  def unpublish
    return unless published?

    update(published_at: nil)
  end

  def archived?
    archived_at.present?    
  end

  def archive
    update(archived_at: Time.zone.current)
  end
  
  def de_archive
    update(archived_at: nil)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update]

  def index
    @genres = Genre.published.alpha_order unless user_signed_in?
    @genres = Genre.alpha_order if user_signed_in?
  end

  def show
    @genre = Genre.includes(:collections).find params[:id]
    @collections = @genre.published_collections.alpha_order unless user_signed_in?
    @collections = @genre.collections.alpha_order if user_signed_in?
  end
  
  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(create_genre_params)
    redirect_to @genre if @genre.save
  end
  
  def update
    @genre = Genre.find params[:id]
    @genre.update(update_genre_params)
    redirect_to @genre
  end

  private

  def create_genre_params
    params.require(:genre).permit(:name)
  end

  def update_genre_params
    params.require(:genre).permit(:published_at)
  end
end

app/views/genres/_genre.html.erb
<li class='list-group-item ps-0 border border-0'>
  <h6>
    <%= link_to genre.name,
            genre_path(genre),
            class: 'text-decoration-none text-black' %>
  </h6>
</li>

app/views/genres/index.html.erb
<% content_for :breadcrumbs do %>
  <%= link_to('Home', root_path, class: 'text-black') %>
  > Genres
<% end %>

<% if user_signed_in? %>
  <small>
    <%= link_to 'new genre', new_genre_path, class: 'text-black'  %>
  </small>
<% end %>

<h2 class='page-heading'>Genres</h2>

<ul class='list-group list-group-flush mt-3'>
  <%= render @genres %>
</ul>

app/views/genres/new.html.erb
<h2 class='page-heading'>Add Genre</h2>

<%= form_with model: @genre do |f| %>
  <%= f.label :name, class: 'form-label' %>
  <%= f.text_field :name, class: 'form-control form-control-sm w-50' %>
  <%= f.submit class: 'mt-3 btn btn-sm btn-secondary' %>
  <%= link_to 'cancel', genres_path, class: 'mt-3 btn btn-sm btn-secondary' %>
<% end %>

app/views/genres/show.html.erb
<% content_for :breadcrumbs do %>
  <%= link_to('Home', root_path, class: 'text-black') %>
  > <%= link_to('Genres', genres_path, class: 'text-black') %>
  > <%= @genre.name %>
<% end %>

<% if user_signed_in? %>
  <small>
    <%= link_to 'add to genre',
                new_genre_collection_path(@genre),
                class: 'text-black' %> | <%= pub_unpub_link(@genre) %>
  </small>
<% end %>

<h2 class='page-heading'><%= @genre.name %></h2>

<ul class='list-group list-group-flush mt-3'>
  <%= render partial: 'collections/collection', collection: @collections %>
</ul>