config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  devise_for :users

  resources :genres, only: %i[index show new create update] do
    resources :collections, only: %i[new]
  end

  resources :collections, only: %i[show create update] do
    resources :writings, only: %i[new]
  end

  resources :writings, only: %i[index show create edit update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/writing.rb
class Writing < ApplicationRecord

  # === relationships

  belongs_to :collection

  # === extensions

  acts_as_list scope: :collection
  has_rich_text :content

  delegate :genre, to: :collection

  # === validations

  # TODO: add this constraint on :name to the database
  validates :name, :content, presence: true

  # === scopes

  scope :by_position, -> { order(:position) }
  scope :published, -> { where.not(published_at: nil) }
  scope :view_order, -> { order(views: :desc) }
  scope :featured, -> { published.where(featured: true).order(created_at: :desc) }

  # === class methods

  def self.publish_by_collection(collection_id)
    where(collection_id: collection_id)
    .each(&:publish)
  end

  def self.archive(collection_id)
    where(collection_id: collection_id)
    .update_all(published_at: nil, archived_at: Time.zone.current)
  end

  # does not re-publish
  def self.de_archive(collection_id)
    where(collection_id: collection_id)
    .update_all(archived_at: nil)
  end

  def self.collate_views
    view_order.includes(:collection).map(&:metadata_view)
  end

  # === instance methods

  def published?
    published_at.present?    
  end

  def publish
    return if archived? || published?

    update(published_at: Time.zone.now)
  end

  def unpublish
    return unless published?

    update(published_at: nil)
  end

  def archived?
    archived_at.present?
  end

  def archive
    return if archived?

    update(published_at: nil, archived_at: Time.zone.current)
  end

  # does not re-publish
  def de_archive
    return unless archived?

    update(archived_at: nil)
  end

  def author_fullname
    "#{author_first}#{(' ' + author_middle) if author_middle?} #{author_last}"
  end

  def pub_date
    published_at&.strftime('%Y') || 'unpublished'
  end

  def metadata_view
    "#{views} | #{name} | #{collection.name}"
  end
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update]
  before_action :find_writing_and_collection, only: %i[show create edit update]

  # Currently, only for showing featured writings
  def index
    redirect_to root_path unless params[:featured]
    @writings = Writing.featured
  end

  def show
    @writing.increment!(:views) unless user_signed_in?
  end

  def new
    @collection = Collection.find params[:collection_id]
    @writing = @collection.writings.build
  end

  def create
    if @writing.save
      redirect_to writing_path(@writing) 
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @writing.update(writing_params)
      redirect_to @writing
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # ====
  private
  # ====

  def writing_params
    params.require(:writing).permit(:collection_id,
                                    :author_first,
                                    :author_middle,
                                    :author_last,
                                    :name,
                                    :published_at,
                                    :content)
  end

  def find_writing_and_collection
    @writing = params[:id] ? Writing.find(params[:id]) : Writing.new(writing_params)
    @collection = @writing.collection
  end
end

app/views/writings/_featured.html.erb
<li class='list-group-item mb-2 ps-0 border border-0'>
  <h6>
    <%= link_to writing.name,
            writing_path(writing),
            class: 'text-decoration-none text-black' %>
  </h6>
  <small><%= writing.genre.name %>, <%= writing.collection.name %></small>
  <small class='d-block'><%= writing.author_fullname %> | <%= writing.pub_date %></small>
</li>

app/views/writings/_form.html.erb
<%= render partial: 'shared/errors', locals: { resource: @writing } %>

<%= form_with model: @writing do |f| %>
  <%= f.hidden_field :collection_id %>

  <%= f.label :author_first, class: 'form-label' %>
  <%= f.text_field :author_first, class: 'form-control form-control-sm w-50' %>

  <%= f.label :author_middle, class: 'form-label' %>
  <%= f.text_field :author_middle, class: 'form-control form-control-sm w-50' %>

  <%= f.label :author_last, class: 'form-label' %>
  <%= f.text_field :author_last, class: 'form-control form-control-sm w-50' %>

  <%= f.label :name, class: 'form-label' %>
  <%= f.text_field :name, class: 'form-control form-control-sm w-50' %>

  <%# TODO: add "publish now" checkbox %>

  <%= f.label :content, class: 'form-label' %>
  <%= f.rich_text_area :content %>

  <%= f.submit class: 'mt-3 btn btn-sm btn-secondary' %>
<% end %>

app/views/writings/_writing.html.erb
<li class='list-group-item ps-0 border border-0'>
  <h6>
    <%= link_to writing.name,
            writing_path(writing),
            class: 'text-decoration-none text-black' %>
  </h6>
</li>

app/views/writings/edit.html.erb
<h2 class='page-heading'>Edit <%= @writing.name %></h2>

<%= render 'form' %>

<%= link_to 'cancel', writing_path(@writing), class: 'mt-3 btn btn-sm btn-secondary' %>

app/views/writings/index.html.erb
<% content_for :breadcrumbs do %>
  <%= link_to('Home', root_path, class: 'text-black') %>
  > Featured
<% end %>

<div class='page-heading'>
  <h2>Featured</h2>
</div>

<ul class='list-group list-group-flush mt-3'>
  <%= render partial: 'featured', collection: @writings, as: :writing %>
</ul>

app/views/writings/new.html.erb
<h2 class='page-heading'>Add to <%= @collection.name %></h2>

<%= render 'form' %>

<%= link_to 'cancel', collection_path(@collection), class: 'mt-3 btn btn-sm btn-secondary' %>

app/views/writings/show.html.erb
<% content_for :breadcrumbs do %>
  <%= link_to('Home', root_path, class: 'text-black') %>
  > <%= link_to('Genres', genres_path, class: 'text-black') %>
  > <%= link_to(@collection.genre.name, genre_path(@collection.genre), class: 'text-black') %>
  > <%= link_to(@collection.name, @collection, class: 'text-black') %>
  > <%= @writing.name %>
<% end %>

<div class='page-heading'>
  <h2><%= @writing.name %></h2>
  <small>
    <%= @writing.author_fullname %> | <%= @writing.pub_date %> 
    <% if user_signed_in? %>
      | <%= link_to 'edit', edit_writing_path(@writing), class: 'text-black' %>
      | <%= pub_unpub_link(@writing) %>
    <% end %>
  </small>
</div>

<article class='w-75'>
  <%= simple_format @writing.content %>
</article>