config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  devise_for :users

  resources :genres, only: %i[index show new create update] do
    resources :collections, only: %i[new]
  end

  resources :collections, only: %i[show create update] do
    resources :writings, only: %i[new]
  end

  resources :writings, only: %i[index show create edit update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing;end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/landing.html.erb
<div class='row w-50 mt-4 justify-content-around'>
  <%= link_to 'Explore the shelves', genres_path, class: 'btn btn-secondary w-auto' %>
  <%= link_to 'Featured', writings_path(featured: true), class: 'btn btn-secondary w-auto' %>
</div>

<%# TODO: make these quotes random from DB records, or API %>
<blockquote class='mt-5'>
  <p>
    There is nothing to writing. All you do is sit down at a typewriter and bleed.
    <small class='d-block'><i>- Ernest Hemmingway</i></small>
  </p>
  <p>
    Don't tell me the moon is shining; show me the glint of light on broken glass.
    <small class='d-block'><i>- Anton Chekhov</i></small>
  </p>
  <p>
    Lock up your libraries if you like;
    <br> but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.
    <small class='d-block'><i>- Virginia Woolf</i></small>
  </p>
</blockquote>